### ISSUE TITLE
Rework of tracking conditions

### ISSUE THREAD

**Issue by sushiat** [opensky-to/agent#79]
- [x] Payload minimum check, higher values are always accepted
- [x] Fuel check with only warnings, but not requirement, low warning, high charge for it
- [x] Real-time clock only as a bonus, changing it should not abort tracking, changing it by more than X minutes disables bonus, a few seconds change should be ignored in case physics engine slowed down

Similar with resuming flight:

- [x] Payload just minimum check
- [x] Fuel this time only a range up or down, but percentage based and not so strict
- [x] Location radius increased by a bit / depending on aircraft type?
